name: Terraform-Apply-and-Run-Ansible

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Infrastructure and Configure
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -no-color
        id: plan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve

      - name: Install Ansible
        run: sudo apt update && sudo apt install -y ansible

  get-ec2-ip:
    name: Get EC2 Instance IP
    runs-on: ubuntu-latest
    steps:
      - name: Get EC2 Instance IP
        run: |
          INSTANCE_ID=$(terraform output ec2_instance_id)
          PUBLIC_IP=$(aws ec2 describe-instances --instance-ids $INSTANCE_ID --query 'Reservations[0].Instances[0].PublicIpAddress' --output text)
          echo "::set-output name=ec2_ip::$PUBLIC_IP"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  run-ansible-playbook:
    name: Run Ansible Playbook
    runs-on: ubuntu-latest
    needs: get-ec2-ip
    steps:
      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i ${{ needs.get-ec2-ip.outputs.ec2_ip }}, playbook.yml
